/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_EVENT_NAME: process.env.NEXT_PUBLIC_EVENT_NAME,
    NEXT_PUBLIC_EVENT_DATE: process.env.NEXT_PUBLIC_EVENT_DATE,
    NEXT_PUBLIC_VENUE_NAME: process.env.NEXT_PUBLIC_VENUE_NAME,
    NEXT_PUBLIC_VENUE_ADDRESS: process.env.NEXT_PUBLIC_VENUE_ADDRESS,
    NEXT_PUBLIC_REGISTRATION_TIME: process.env.NEXT_PUBLIC_REGISTRATION_TIME,
    NEXT_PUBLIC_SHOTGUN_START: process.env.NEXT_PUBLIC_SHOTGUN_START,
    NEXT_PUBLIC_INDIVIDUAL_PRICE: process.env.NEXT_PUBLIC_INDIVIDUAL_PRICE,
    NEXT_PUBLIC_TEAM_PRICE: process.env.NEXT_PUBLIC_TEAM_PRICE,
  },
}

module.exports = nextConfig